### PR TITLE
👷 Improve GitHub workflows

### PR DESCRIPTION
**Pull request by AlexV525**
Improve the workflow configuration between packages.

image
image

The PR also tried to solve #48 but got no luck. I'll update the tests in another PR.

### CODE REVIEW

**Comment by AlexV525** [comment]
@ueman Should we fix tests before merging or let it be red at present?

**Comment by ueman** [comment]
Fixed the changelog in https://github.com/cfug/diox/pull/54

**Review by ueman — APPROVED** [review]

**Comment by AlexV525** [comment]
> Fixed the changelog in #54

https://github.com/cfug/diox/actions/runs/3784661929/jobs/6434142716 is still failing.

**Comment by ueman** [comment]
Oh no, I'll give it a look later today.

**Pull request merged**
