### PR TITLE
Update pretty_dio_logger package to support diox

### PR DESCRIPTION
**Pull request by dmakwt**
Signed-off-by: Dhari <dmakwt@gmail.com>

### New Pull Request Checklist

- [x] I have read the [Documentation](https://pub.dev/documentation/diox/latest/)
- [x] I have searched for a similar pull request in the [project](https://github.com/cfug/diox/pulls) and found none
- [x] I have updated this branch with the latest `main` branch to avoid conflicts (via merge from master or rebase)
- [ ] I have added the required tests to prove the fix/feature I'm adding
- [x] I have updated the documentation (if necessary)
- [ ] I have run the tests without failures

### CODE REVIEW

**Comment by ueman** [comment]
Does it make sense to move this package directly into diox? The logger has no other dependencies so it would be easy and lightweight to integrate directly into diox. It also works with tree shaking, so it doesn't bloat users code if they don't use it.

**Comment by dmakwt** [comment]
I already published it to [pub.dev](https://pub.dev/packages/pretty_diox_logger), but we can move it to the [plugins folders](https://github.com/cfug/diox/tree/main/plugins).

**Comment by dmakwt** [comment]
Or we can move it to https://github.com/cfug/diox/tree/main/dio/lib/src/interceptors

**Comment by AlexV525** [comment]
> Does it make sense to move this package directly into diox? The logger has no other dependencies so it would be easy and lightweight to integrate directly into diox. It also works with tree shaking, so it doesn't bloat users code if they don't use it.

Merging plugins into the base repo will increase the complexity during publishment, mono repos doesn't have well controlled permission handling, and it cand ends up like the old dio. So I would suggest to keep minimum plugins in the base repo, until it'll widely benifit users. And that doesn't mean the plugin is not worth it.

**Comment by AlexV525** [comment]
@dmakwt Thanks for your contribution. I was wondering if the package has a proper discussion with @Milad-Akarie, it'll be better if the original plugin's author can maintain it as well.

**Comment by dmakwt** [comment]
I saw the last update for the package was in 2021, and I did not see any interaction inside the pull requests sections. So I have mentioned this package "Forked from pretty_dio_logger to support Diox"

**Comment by dmakwt** [comment]
I created a [pull request](https://github.com/Milad-Akarie/pretty_dio_logger/pull/27) inside his package. As a temporary solution, I will keep publishing the [package to pub.dev](https://pub.dev/packages/pretty_diox_logger).

**Review by ueman — APPROVED** [review]

**Pull request merged**
