### PR TITLE
Use pubspec_overrides and improve workflows

### PR DESCRIPTION
**Pull request by kuhnroyal**
`pubspec_overrides` helps during development and doesn't interfere with publishing.

### New Pull Request Checklist

- [x] I have read the [Documentation](https://pub.dev/documentation/diox/latest/)
- [x] I have searched for a similar pull request in the [project](https://github.com/cfug/diox/pulls) and found none
- [x] I have updated this branch with the latest `main` branch to avoid conflicts (via merge from master or rebase)
- [ ] I have added the required tests to prove the fix/feature I'm adding
- [ ] I have updated the documentation (if necessary)
- [x] I have run the tests without failures

### CODE REVIEW

**Review by ueman — COMMENTED** [review]
Should there be a `.pubignore` file which ignores the override yaml files?

**Comment by kuhnroyal** [comment]
I believe they are ignored by default

**Comment by AlexV525** [comment]
Yes. Overrides only work when running `get` and `upgrade` in its directory.

**Comment by AlexV525** [comment]
Can you do the same thing with the plugin `native_diox_adapter`?

**Comment by ueman** [comment]
> Can you do the same thing with the plugin `native_diox_adapter`?

It's already included in this PR.

**Review by AlexV525 — APPROVED** [review]

**Pull request merged**
